Repository fiit-tp7-2023/frontend, pull requests merged in 2023-12, with the labels that each got.

#60 AB#194 Add logo
  components/project/layout/NavigationComponent.vue
  components/team-info/layout/TeamNavigation.vue
  public/images/logo-pink.svg
Labels: small, waiting-for-review

#61 #204 Create docker files
  Dockerfile
  docker-compose.yml
Labels: small, waiting-for-review

#62 #204 Update docker files
  docker-compose.yml
Labels: small, waiting-for-review

#59 AB#195 Update project section button design
  components/team-info/sections/TeamInfo.vue
Labels: small, waiting-for-review

#57 AB#178 Display correlated addresses
  components/project/sections/NftInfo.vue
  components/project/sections/TransactionsSection.vue
  composables/pagination.ts
  utils/pagination.ts
Labels: medium, waiting-for-review

#63 AB#204 Update docker files
  Dockerfile
Labels: small, waiting-for-review

#64 AB#204 Update docker files
  docker-compose.yml
Labels: small, waiting-for-review

#66 Ab#211 Update frontend schema
  components/project/sections/NftInfo.vue
  components/project/sections/TransactionsSection.vue
  types/dtos/transaction.ts
  types/forms/transaction.ts
  types/nodes/address-node.ts
  types/nodes/nft-node.ts
Labels: small, waiting-for-review

#67 AB#189 display image
  components/project/layout/NavigationComponent.vue
  components/project/sections/NftInfo.vue
  components/team-info/layout/TeamNavigation.vue
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#68 Add documents
  .vscode/settings.json
  content/minute-books/minute-book-6.md
  content/minute-books/minute-book-7.md
  content/minute-books/minute-book-8.md
  content/minute-books/minute-book-summary.md
  content/retrospectives/retrospective-3.md
  content/retrospectives/retrospective-4.md
  content/retrospectives/retrospective-summary.md
  public/images/retrospectives/retrospective-3.png
  public/images/retrospectives/retrospective-4.png
  public/minute-books/minute-book-6.pdf
  public/minute-books/minute-book-7.pdf
  public/minute-books/minute-book-8.pdf
  public/minute-books/minute-book-summary.pdf
  public/retrospectives/retrospective-3.pdf
  public/retrospectives/retrospective-4.pdf
  public/retrospectives/retrospective-summary.pdf
Labels: large, waiting-for-review

#69 AB#179 Add link to Etherscan
  .vscode/settings.json
  components/project/sections/NftInfo.vue
  pages/index.vue
  pages/project/index.vue
  pages/project/login.vue
  public/favicon.ico
Labels: small, waiting-for-review

#70 AB#203 Update github workflow to clean unused data before building
  .github/workflows/main.yml
Labels: small, waiting-for-review

#71 :bug: typo in Viki's name
  components/team-info/sections/TeamSection.vue
Labels: small, waiting-for-review

#72 Small cleanup
  components/project/sections/TransactionsSection.vue
  components/team-info/sections/MemberComponent.vue
Labels: small, waiting-for-review

#73 Use document API to download documents
  components/team-info/sections/DocumentsSection.vue
Labels: small, waiting-for-review

#74 Add document API logs
  server/api/document/index.ts
Labels: small, waiting-for-review

#76 Fix puppeteer issues and remove unnecessary files
  Dockerfile
  public/minute-books/minute-book-1.pdf
  public/minute-books/minute-book-2.pdf
  public/minute-books/minute-book-3.pdf
  public/minute-books/minute-book-4.pdf
  public/minute-books/minute-book-6.pdf
  public/minute-books/minute-book-7.pdf
  public/minute-books/minute-book-8.pdf
  public/minute-books/minute-book-summary.pdf
  public/retrospectives/retrospective-1.pdf
  public/retrospectives/retrospective-2.pdf
  public/retrospectives/retrospective-3.pdf
  public/retrospectives/retrospective-4.pdf
  public/retrospectives/retrospective-summary.pdf
  server/api/document/index.ts
  server/services/document.ts
Labels: small, waiting-for-review

#75 Design proposal
  .vscode/settings.json
  app.vue
  components/team-info/layout/TeamNavigation.vue
  components/team-info/sections/DocumentsSection.vue
  components/team-info/sections/ProjectInfo.vue
  components/team-info/sections/TeamInfo.vue
  components/team-info/sections/TeamSection.vue
  components/team-info/sections/TimelineComponent.vue
  nuxt.config.ts
  pages/index.vue
  public/images/graph.png
  public/images/screen.png
Labels: medium, waiting-for-review
