Repository fiit-tp7-2023/frontend, pull requests merged in 2023-11, with the labels that each got.

#14 AB#69 Add attributes property to NFT node
  types/nodes/attribute.ts
  types/nodes/nft-node.ts
Labels: small, waiting-for-review

#15 AB#109 - Component for shorter ETH and NFT addresses
  app.vue
  components/project/other/TruncatedAddressComponent.vue
  components/project/sections/TransactionsSection.vue
  constants/regex.ts
  package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#16 AB#125 Setup Nuxt Content
  .vscode/extensions.json
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#19 AB#126 Create components for nuxt content
  components/content/ProseBlockquote.vue
  components/content/ProseCode.vue
  components/content/ProseH1.vue
  components/content/ProseH2.vue
  components/content/ProseH3.vue
  components/content/ProseH4.vue
  components/content/ProseH5.vue
  components/content/ProseH6.vue
  components/content/ProseHr.vue
  components/content/ProseLi.vue
  components/content/ProseOl.vue
  components/content/ProseP.vue
  components/content/ProseTable.vue
  components/content/ProseUl.vue
Labels: small, waiting-for-review

#18 AB#127 Move markdown documents to Nuxt content
  content/minute-books/minute-book-1.md
  content/minute-books/minute-book-2.md
  content/minute-books/minute-book-3.md
  content/minute-books/minute-book-4.md
  content/retrospectives/retrospective-1.md
  content/retrospectives/retrospective-2.md
  public/images/retrospectives/retrospective-1.png
  public/images/retrospectives/retrospective-2.png
Labels: large, waiting-for-review

#20 AB#16 Create component for documents
  components/team-info/sections/DocumentsSection.vue
  components/team-info/sections/TeamInfo.vue
  nuxt.config.ts
  pages/index.vue
Labels: small, waiting-for-review

#21 AB#128 Fix colors
  app.vue
  components/project/layout/FooterComponent.vue
  components/project/layout/NavigationComponent.vue
  components/project/sections/TransactionsSection.vue
  components/team-info/layout/TeamFooter.vue
  components/team-info/layout/TeamNavigation.vue
  components/team-info/sections/TeamInfo.vue
  components/team-info/sections/TeamMemberComponent.vue
  components/team-info/sections/TeamSection.vue
  layouts/default.vue
  pages/index.vue
  pages/project/login.vue
Labels: medium, waiting-for-review

#23 AB#129 Download documents
  components/team-info/sections/DocumentsSection.vue
  content/minute-books/minute-book-1.md
  content/minute-books/minute-book-2.md
  content/minute-books/minute-book-3.md
  content/minute-books/minute-book-4.md
  content/retrospectives/retrospective-1.md
  content/retrospectives/retrospective-2.md
  public/minute-books/minute-book-1.pdf
  public/minute-books/minute-book-2.pdf
  public/minute-books/minute-book-3.pdf
  public/minute-books/minute-book-4.pdf
  public/retrospectives/retrospective-1.pdf
  public/retrospectives/retrospective-2.pdf
Labels: small, waiting-for-review

#24 AB#133 Rename transaction search endpoint
  components/project/sections/TransactionsSection.vue
  server/api/transaction/index.ts
  server/services/transaction.ts
Labels: small, waiting-for-review

#22 AB#109 Shorter eth address component
  components/project/other/TruncatedAddressComponent.vue
Labels: small, waiting-for-review

#25 AB#111 Web layout
  app.vue
  components/project/layout/NavigationComponent.vue
  components/project/sections/TransactionsSection.vue
  components/team-info/layout/TeamNavigation.vue
  layouts/team.vue
  pages/index.vue
Labels: medium, waiting-for-review

#26 AB#143 Provide access to project section in vercel preview deployments
  middleware/redirect.ts
  nuxt.config.ts
  pages/project/login.vue
Labels: small, waiting-for-review

#27 #145 Edit API according to the backend API
  server/api/nft/[id].ts
  server/api/tag/index.ts
  server/services/nft.ts
  server/services/tag.ts
  server/services/transaction.ts
  types/dtos/index.ts
  types/dtos/nft.ts
  types/dtos/tag.ts
  types/dtos/transaction.ts
  types/nodes/attribute.ts
  types/nodes/nft-node.ts
Labels: small, waiting-for-review

#29 AB#116 Added responsiveness to team section
  components/team-info/sections/TeamMemberComponent.vue
  components/team-info/sections/TeamSection.vue
Labels: small, waiting-for-review

#30 AB#123-curved-timeline-(fixed)
  components/team-info/sections/TimelineComponent.vue
  pages/index.vue
Labels: medium, waiting-for-review

#31 AB#159 Center the timeline component
  components/team-info/sections/TimelineComponent.vue
Labels: small, waiting-for-review

#45 AB#171 Responsive transaction table
  components/project/sections/TransactionsSection.vue
Labels: small, waiting-for-review

#46 AB#172 Implement error handling
  app.vue
  components/project/other/ServerError.vue
  components/project/sections/TransactionsSection.vue
  server/errors/index.ts
  server/utils/api.ts
  types/error.ts
Labels: medium, waiting-for-review

#38 AB#164 add events to timeline
  components/team-info/sections/TimelineComponent.vue
Labels: small, waiting-for-review

#47 Ab#185 document button eye
  components/team-info/sections/DocumentsSection.vue
Labels: small, waiting-for-review

#49 AB#190 update eslint config
  .eslintrc
Labels: small, waiting-for-review

#50 AB#174 Filter transactions by NFT tags
  components/project/sections/TransactionsSection.vue
  components/team-info/sections/TimelineComponent.vue
  types/dtos/pagination.ts
  types/dtos/tag.ts
  types/forms/transaction.ts
Labels: medium, waiting-for-review

#52 Transaction bug fix
  components/project/sections/TransactionsSection.vue
Labels: small, waiting-for-review

#54 AB#170 Add skeleton loading
  components/project/sections/TransactionsSection.vue
Labels: small, waiting-for-review

#56 AB#176 Add navigation to NFT page from table
  components/project/other/TruncatedAddressComponent.vue
Labels: small, waiting-for-review

#55 AB#188 Add NFT tags
  components/project/sections/NftInfo.vue
Labels: small, waiting-for-review
