Repository fiit-tp7-2023/frontend, pull requests merged in 2023-10, with the labels that each got.

#2 Google authentication, session management, initial routing - AB#42
  .env.example
  app.vue
  layouts/default.vue
  layouts/team.vue
  nuxt.config.ts
  package.json
  pages/index.vue
  pages/project/index.vue
  pages/project/login.vue
  server/api/auth/[...].ts
  types/auth/RefreshGoogleTokenRequest.ts
  types/auth/RefreshGoogleTokenResponse.ts
  types/auth/next-auth.d.ts
Labels: enhancement

#4 AB#76 Fetch example & Debugger setting
  .vscode/launch.json
  pages/project/index.vue
  pnpm-lock.yaml
  server/api/weather.ts
  server/config/api.ts
  server/services/weather.ts
  server/utils/api.ts
  types/weather.ts
Labels: enhancement

#8 AB#70 Login styling
  .vscode/extensions.json
  README.md
  components/project/layout/FooterComponent.vue
  components/project/layout/NavigationComponent.vue
  pages/project/login.vue
Labels: small, waiting-for-review

#10 AB#69 Transaction searching
  .env.example
  components/project/sections/TransactionsSection.vue
  nuxt.config.ts
  pages/project/index.vue
  server/api/auth/[...].ts
  server/api/transaction/[id].ts
  server/api/transaction/search.ts
  server/config/api.ts
  server/services/transaction.ts
  server/services/weather.ts
  server/utils/api.ts
  types/auth/RefreshGoogleTokenRequest.ts
  types/auth/RefreshGoogleTokenResponse.ts
  types/dtos/index.ts
  types/dtos/pagination.ts
  types/dtos/refresh-google-token.ts
  types/dtos/transaction.ts
  types/forms/index.ts
  types/forms/transaction.ts
  types/nodes/address-node.ts
  types/nodes/index.ts
  types/nodes/nft-node.ts
  types/nodes/transaction-node.ts
  types/weather.ts
Labels: large, waiting-for-review

#9 AB#66 Add team member component and team section component
  components/team-info/sections/TeamMemberComponent.vue
  components/team-info/sections/TeamSection.vue
  pages/index.vue
Labels: small, waiting-for-review

#11 Change deploy url
  nuxt.config.ts
Labels: small, waiting-for-review

#12 Tailwind/Naive nuxt modules
  .vscode/settings.json
  app.vue
  assets/css/tailwind.css
  components/project/layout/FooterComponent.vue
  components/project/layout/NavigationComponent.vue
  components/project/sections/TransactionsSection.vue
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/index.vue
  pages/project/login.vue
  plugins/naive-ui.ts
  pnpm-lock.yaml
  tailwind.config.js
Labels: enhancement, large, waiting-for-review

#13 AB#63 prepare layout
  .vscode/settings.json
  components/team-info/layout/TeamFooter.vue
  components/team-info/layout/TeamNavigation.vue
  components/team-info/sections/MemberComponent.vue
  components/team-info/sections/TeamInfo.vue
  components/team-info/sections/TeamSection.vue
  layouts/team.vue
  pages/index.vue
Labels: medium, waiting-for-review
